name: "cargo build/test"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with: { submodules: recursive }
    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
